[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

# Los íconos casi nunca cambian, esos sí pueden cachearse largo tiempo
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
